* Vulkan Renderer Implementation
  
A (not so) simple vulkan renderer, targeting ps1-ps2 capabilities.

* Roadmap
  
Required Features:
- [X] Setup Geometry pass with support for debug rendering (wireframe normaldirection).
- [X] Pimpl Abstraction Interface.
- [X] Model & Texture support - includes loaders and renderer handling.
- [X] LightCasters - support basic untextured lights (directional, point, spot)
- [X] Shadowmaps - simple support for a single directional and spot light.
- [ ] gltf loading (not animated).
- [ ] Animated meshes - limit support to gltf models.
- [ ] GUI using ImGui - can maybe be exposed as transitive dependency.
- [ ] Add a gpu physical device selection method.
- [ ] Changeable Background color.
- [ ] Windows support.
   
Optional Features:
- [ ] Shadowmaps - multiple spot lights.
- [ ] Fix point interpolation for textures.
- [ ] Fix screen extent and render extents, so they are disconnected.
- [ ] Model tinting for post-lighting manipulation (useful for dark/light models).
- [ ] Async render thread.
- [ ] Animation Blending.
- [ ] Soft Shadows.
- [ ] Decals.
- [ ] Skybox.
- [ ] Billboards.
- [ ] Transparency (the sorted kind).
- [ ] fix commandbuffer connection between rendering and presentation - potentially just disallow headless rendering.
- [ ] disable validation layer for release builds.
- [ ] move stb_image and objloader headers behind interface.
- [ ] Simple SSAO pass.
- [ ] Add capability query of different features and disable renderer steps accordingly.
- [ ] Implement format fallback alternatives for textures.
- [ ] Simpler abstraction.
- [ ] Resource Managers (that are also loaders) - support for textures and meshes.
- [ ] FOV render culling.
- [ ] Gizmos using ImGuizmo.

* Known Bugs
  
Swapping out order of renderables so sms isint the first, crashes the system, something about binding textures i think.
 
alidation Error: [ VUID-vkCmdDraw-None-08600 ] | MessageID = 0x4768cf39
vkCmdDraw(): The VkPipeline 0xa500000000a5 (created with VkPipelineLayout 0x8c000000008c) statically uses descriptor set 6, but all sets 0 to 6 are not compatible with the pipeline layout bound with vkCmdBindDescriptorSets (VkPipelineLayout 0x8c000000008c)
The set (6) is out of bounds for the number of sets bound (5)
Hint: Make sure the previous calls to vkCmdBindDescriptorSets has all sets bound that are needed.
The Vulkan spec states: For each set n that is statically used by a bound shader, a descriptor set must have been bound to n at the same pipeline bind point, with a VkPipelineLayout that is compatible for set n, with the VkPipelineLayout used to create the current VkPipeline or the VkDescriptorSetLayout array used to create the current VkShaderEXT , as described in Pipeline Layout Compatibility (https://vulkan.lunarg.com/doc/view/1.4.313.0/linux/antora/spec/latest/chapters/drawing.html#VUID-vkCmdDraw-None-08600)
Objects: 2
    [0] VkPipeline 0xa500000000a5
    [1] VkPipelineLayout 0x8c000000008c

