* Vulkan Renderer Implementation
  
A (not so) simple vulkan renderer, targeting ps1-ps2 capabilities.

* Roadmap
  
Required Features:
- [X] Setup Geometry pass with support for debug rendering (wireframe normaldirection).
- [X] Pimpl Abstraction Interface.
- [X] Model & Texture support - includes loaders and renderer handling.
- [X] LightCasters - support basic untextured lights (directional, point, spot)
- [X] Shadowmaps - simple support for a single directional and spot light.
- [X] gltf loading (not animated).
- [X] Animated meshes - limit support to gltf models.
- [X] Shadows for animated meshes.
- [ ] Support vertex indices.
- [ ] Investigate weird singular vertices that has wrong animated transformations (potentially fixed by supporting indices).
- [ ] Add a gpu physical device selection method.
- [ ] Changeable Background color.
- [ ] Windows support.
   
Less Important Features:
- [ ] add a shadow_bakeable boolean to shadow pass and draw them into an "initial" shadow texture for orthographic shadows to be based on.
- [ ] GUI using ImGui - can maybe be exposed as transitive dependency.
- [ ] Custom static mesh binary format, something that has a ascii name + version, then a binary blob that is just <TYPE><SIZE><DATA><TYPE><SIZE><DATA> so it is really easy and quick to parse (this must support changing endians aswell). The format should be directly copyable to the gpu. 
- [ ] Make logger a singleton so it actually can be used everywhere instead of passed all over. It should probably be multithread applicable?
- [ ] non-animated Vertex color pipeline.
- [ ] Shadowmaps - multiple spot lights.
- [ ] Fix point interpolation for textures.
- [ ] Fix screen extent and render extents, so they are disconnected.
- [ ] Model tinting for post-lighting manipulation (useful for dark/light models).
- [ ] Async render thread.
- [ ] Animation Blending.
- [ ] Soft Shadows.
- [ ] Decals & Billboards (Alpha discardable).
- [ ] instanced rendering for non-animated models.
- [ ] Skybox.
- [ ] Transparency (the manually sorted kind).
- [ ] fix commandbuffer connection between rendering and presentation - potentially just disallow headless rendering.
- [ ] disable validation layer for release builds.
- [ ] move stb_image and objloader headers behind interface.
- [ ] Simple SSAO pass.
- [ ] Add capability query of different features and disable renderer steps accordingly.
- [ ] Implement format fallback alternatives for textures.
- [ ] Simpler abstraction.
- [ ] Resource Managers (that are also loaders) - support for textures and meshes.
- [ ] FOV render culling.
- [ ] Gizmos using ImGuizmo.
